# Generated by Django 5.2 on 2025-04-06 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade_Ensino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria_presencial', models.PositiveSmallIntegerField()),
                ('carga_horaria_remota', models.PositiveSmallIntegerField()),
                ('referencias_basicas', models.TextField()),
                ('referencias_complementares', models.TextField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplinas.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_modalidade_ensino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplinas.modalidade_ensino'),
        ),
    ]
