# Generated by Django 5.2 on 2025-04-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='codigo',
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
