# Generated by Django 5.2 on 2025-04-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '0002_remove_disciplina_codigo_curso_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='id_modalidade_ensino',
            new_name='modalidade_ensino',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='id_curso',
            new_name='curso',
        ),
    ]
