# Generated by Django 5.2 on 2025-05-10 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '0003_rename_id_modalidade_ensino_curso_modalidade_ensino_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_periodo', models.PositiveSmallIntegerField()),
                ('turma', models.CharField(max_length=10)),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplinas.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
