# Generated by Django 5.2 on 2025-05-12 21:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '0004_disciplinaprofessor'),
        ('ppt', '0002_status_remove_ppt_disciplina_remove_ppt_turma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisciplinaProfessor',
            new_name='DisciplinaMinistrada',
        ),
        migrations.RenameModel(
            old_name='Modalidade_Ensino',
            new_name='ModalidadeEnsino',
        ),
    ]
