# Generated by Django 5.2 on 2025-05-12 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disciplinas', '0005_rename_disciplinaprofessor_disciplinaministrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaministrada',
            name='ano',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
