# Generated by Django 5.2 on 2025-04-07 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Disciplinas', '0003_rename_id_modalidade_ensino_curso_modalidade_ensino_and_more'),
        ('calendario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeAvaliativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ppt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_periodo', models.PositiveSmallIntegerField()),
                ('turma', models.CharField(max_length=10)),
                ('trimestre_semestre', models.CharField(max_length=10)),
                ('ementa', models.TextField()),
                ('objetivos', models.TextField()),
                ('cidade', models.CharField(max_length=50)),
                ('aulas_segunda', models.PositiveSmallIntegerField()),
                ('aulas_terca', models.PositiveSmallIntegerField()),
                ('aulas_quarta', models.PositiveSmallIntegerField()),
                ('aulas_quinta', models.PositiveSmallIntegerField()),
                ('aulas_sexta', models.PositiveSmallIntegerField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Disciplinas.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('conteudo_programatico', models.CharField(max_length=50)),
                ('metodologia', models.CharField(max_length=50)),
                ('atividade_avaliativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.atividadeavaliativa')),
                ('ppt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.ppt')),
            ],
        ),
        migrations.AddField(
            model_name='atividadeavaliativa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppt.tipoatividade'),
        ),
    ]
