# Generated by Django 5.2 on 2025-04-07 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NomeFeriadoMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SabadoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia_referente', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeriadoFixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('calendario', models.ManyToManyField(to='calendario.calendario')),
            ],
        ),
        migrations.CreateModel(
            name='FeriadoMovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.nomeferiadomovel')),
            ],
        ),
    ]
