# Generated by Django 5.2 on 2025-05-12 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriadofixo',
            name='calendario',
        ),
        migrations.CreateModel(
            name='FeriadoFixoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.calendario')),
                ('feriado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendario.feriadofixo')),
            ],
        ),
    ]
